export const pages = {
  main: '/',
  setup: {
    desktopPaths: '/setup/desktop-paths',
    desktopScrape: '/setup/desktop-scrape',
    webPaths: '/setup/web-paths',
  },
  progressTracker: {
    index: '/progress-tracker',
    secrets: '/progress-tracker/secrets',
    achievementPillar: '/progress-tracker/secrets/pillar',
  },
  wiki: {
    perks: '/wiki/perks',
    perkDetail: (perkId: string) => '/wiki/perks/' + perkId,
    spells: '/wiki/spells',
    spellDetail: (spellId: string) => '/wiki/spells/' + spellId,
    enemies: '/wiki/enemies',
    enemyDetail: (enemyId: string) => '/wiki/enemies/' + enemyId,
    materials: '/wiki/materials',
    materialDetail: (materialId: string) => '/wiki/materials/' + materialId,
    materialsTree: '/wiki/materials-tree',
  },
  holidays: '/holidays',
  sessions: '/sessions',
  deathMap: '/death-map',
  bonesWands: '/bones-wands',
  settings: {
    index: '/settings',
    cursorWandPicker: '/settings/cursor-wand-picker',
  },
  currentRun: '/current-run',
  credits: '/credits',
  sandbox: '/sandbox',
};
